-- Dummy Member with ID 100
INSERT INTO member (
    member_id, 
    email, 
    password, 
    name, 
    nickname, 
    birth_date, 
    gender, 
    phone_number, 
    role, 
    status, 
    profile_image_url, 
    address_road, 
    introduction, 
    latitude, 
    longitude, 
    district_code, 
    sweetness, 
    created_at, 
    updated_at
) VALUES (
    100, 
    'dummy@example.com', 
    '$2a$10$4pyW8SwZmR0msFWv5RxWfu.xO0mo0vQZiZGaG7ZQDjY.UQMB6thDa',
    'Dummy User', 
    'Dummy', 
    '1990-01-01', 
    'MALE', 
    '010-1234-5678', 
    'DISABLED',
    'ACTIVE',
    NULL, 
    '서울특별시 강남구', 
    'Hello, I am a dummy user for testing.', 
    37.517235, 
    127.047325, 
    '1168000000', 
    40.00,
    NOW(), 
    NOW()
);
