-- ========================================
-- V6: 테스트 회원 데이터 삽입
-- ========================================
-- 장애인 6명 (100, 200, 300, 400, 500, 600)
-- 도우미 4명 (700, 800, 900, 1000)

-- 회원 1: 장애인 (김철수, 60대 남성)
INSERT INTO member (
    member_id,
    email,
    password,
    name,
    nickname,
    birth_date,
    gender,
    phone_number,
    role,
    status,
    profile_image_url,
    address_road,
    introduction,
    latitude,
    longitude,
    district_code,
    sweetness,
    created_at,
    updated_at
) VALUES (
    100,
    'kim.cheolsu@example.com',
    '$2a$10$4pyW8SwZmR0msFWv5RxWfu.xO0mo0vQZiZGaG7ZQDjY.UQMB6thDa',
    '김철수',
    '김철수',
    '1960-05-15',
    'MALE',
    '010-1001-0001',
    'DISABLED',
    'ACTIVE',
    'https://example.com/profiles/admin.jpg',
    '서울특별시 강남구 역삼동',
    '안녕하세요, 김철수입니다. 일상생활에 도움이 필요합니다.',
    37.5012,
    127.0396,
    '1168010500',
    40.00,
    NOW(),
    NOW()
) ON DUPLICATE KEY UPDATE
    email = VALUES(email),
    password = VALUES(password),
    name = VALUES(name),
    nickname = VALUES(nickname),
    birth_date = VALUES(birth_date),
    gender = VALUES(gender),
    phone_number = VALUES(phone_number),
    role = VALUES(role),
    status = VALUES(status),
    profile_image_url = VALUES(profile_image_url),
    address_road = VALUES(address_road),
    introduction = VALUES(introduction),
    latitude = VALUES(latitude),
    longitude = VALUES(longitude),
    district_code = VALUES(district_code),
    sweetness = VALUES(sweetness),
    updated_at = NOW();

-- 회원 2: 장애인 (김민수, 70대 남성)
INSERT INTO member (
    member_id,
    email,
    password,
    name,
    nickname,
    birth_date,
    gender,
    phone_number,
    role,
    status,
    profile_image_url,
    address_road,
    introduction,
    latitude,
    longitude,
    district_code,
    sweetness,
    created_at,
    updated_at
) VALUES (
    200,
    'kim.minsu@example.com',
    '{bcrypt}$2a$10$8.UnVuG9HHgffUDAlk8qfOuVGkqRzgVymGe07xd00DMxs.TVuHOnu',
    '김민수',
    '김민수',
    '1955-08-20',
    'MALE',
    '010-2001-0001',
    'DISABLED',
    'ACTIVE',
    'https://example.com/profiles/member200.jpg',
    '서울특별시 송파구 잠실동',
    '안녕하세요, 김민수입니다. 외출 시 도움이 필요합니다.',
    37.4837,
    127.0324,
    '1165010100',
    40.00,
    NOW(),
    NOW()
);

-- 회원 3: 장애인 (이영희, 60대 여성)
INSERT INTO member (
    member_id,
    email,
    password,
    name,
    nickname,
    birth_date,
    gender,
    phone_number,
    role,
    status,
    profile_image_url,
    address_road,
    introduction,
    latitude,
    longitude,
    district_code,
    sweetness,
    created_at,
    updated_at
) VALUES (
    300,
    'lee.younghee@example.com',
    '{bcrypt}$2a$10$8.UnVuG9HHgffUDAlk8qfOuVGkqRzgVymGe07xd00DMxs.TVuHOnu',
    '이영희',
    '이영희',
    '1965-03-10',
    'FEMALE',
    '010-3001-0001',
    'DISABLED',
    'ACTIVE',
    'https://example.com/profiles/member300.jpg',
    '서울특별시 광진구 광장동',
    '안녕하세요, 이영희입니다. 가사 도움이 필요합니다.',
    37.5133,
    127.1000,
    '1171010100',
    40.00,
    NOW(),
    NOW()
);

-- 회원 4: 장애인 (박민수, 50대 남성)
INSERT INTO member (
    member_id,
    email,
    password,
    name,
    nickname,
    birth_date,
    gender,
    phone_number,
    role,
    status,
    profile_image_url,
    address_road,
    introduction,
    latitude,
    longitude,
    district_code,
    sweetness,
    created_at,
    updated_at
) VALUES (
    400,
    'park.minsu@example.com',
    '{bcrypt}$2a$10$8.UnVuG9HHgffUDAlk8qfOuVGkqRzgVymGe07xd00DMxs.TVuHOnu',
    '박민수',
    '박민수',
    '1970-11-25',
    'MALE',
    '010-4001-0001',
    'DISABLED',
    'ACTIVE',
    'https://example.com/profiles/member400.jpg',
    '서울특별시 광진구 구의동',
    '안녕하세요, 박민수입니다. 병원 동행이 필요합니다.',
    37.5388,
    127.1236,
    '1174010100',
    40.00,
    NOW(),
    NOW()
);

-- 회원 5: 장애인 (최은정, 60대 여성)
INSERT INTO member (
    member_id,
    email,
    password,
    name,
    nickname,
    birth_date,
    gender,
    phone_number,
    role,
    status,
    profile_image_url,
    address_road,
    introduction,
    latitude,
    longitude,
    district_code,
    sweetness,
    created_at,
    updated_at
) VALUES (
    500,
    'choi.eunjung@example.com',
    '{bcrypt}$2a$10$8.UnVuG9HHgffUDAlk8qfOuVGkqRzgVymGe07xd00DMxs.TVuHOnu',
    '최은정',
    '최은정',
    '1958-07-30',
    'FEMALE',
    '010-5001-0001',
    'DISABLED',
    'ACTIVE',
    'https://example.com/profiles/member500.jpg',
    '서울특별시 서대문구 연희동',
    '안녕하세요, 최은정입니다. 청소 도움이 필요합니다.',
    37.5443,
    127.0557,
    '1120010100',
    40.00,
    NOW(),
    NOW()
);

-- 회원 6: 장애인 (정수진, 50대 성별미상)
INSERT INTO member (
    member_id,
    email,
    password,
    name,
    nickname,
    birth_date,
    gender,
    phone_number,
    role,
    status,
    profile_image_url,
    address_road,
    introduction,
    latitude,
    longitude,
    district_code,
    sweetness,
    created_at,
    updated_at
) VALUES (
    600,
    'jung.sujin@example.com',
    '{bcrypt}$2a$10$8.UnVuG9HHgffUDAlk8qfOuVGkqRzgVymGe07xd00DMxs.TVuHOnu',
    '정수진',
    '정수진',
    '1975-02-14',
    'NONE',
    '010-6001-0001',
    'DISABLED',
    'ACTIVE',
    'https://example.com/profiles/member600.jpg',
    '서울특별시 동대문구 청량리동',
    '안녕하세요, 정수진입니다. 말벗이 필요합니다.',
    37.5833,
    127.0913,
    '1126010100',
    40.00,
    NOW(),
    NOW()
);

-- 회원 7: 도우미 (강지훈, 30대 남성)
INSERT INTO member (
    member_id,
    email,
    password,
    name,
    nickname,
    birth_date,
    gender,
    phone_number,
    role,
    status,
    profile_image_url,
    address_road,
    introduction,
    latitude,
    longitude,
    district_code,
    sweetness,
    created_at,
    updated_at
) VALUES (
    700,
    'kang.jihoon@example.com',
    '$2a$10$4pyW8SwZmR0msFWv5RxWfu.xO0mo0vQZiZGaG7ZQDjY.UQMB6thDa',
    '강지훈',
    '강지훈',
    '1990-09-05',
    'MALE',
    '010-7001-0001',
    'HELPER',
    'ACTIVE',
    'https://example.com/profiles/member700.jpg',
    '서울특별시 성북구 삼선동',
    '안녕하세요, 강지훈입니다. 성실하게 도와드리겠습니다.',
    37.5894,
    127.0582,
    '1123010100',
    40.00,
    NOW(),
    NOW()
);

-- 회원 8: 도우미 (윤서연, 30대 여성)
INSERT INTO member (
    member_id,
    email,
    password,
    name,
    nickname,
    birth_date,
    gender,
    phone_number,
    role,
    status,
    profile_image_url,
    address_road,
    introduction,
    latitude,
    longitude,
    district_code,
    sweetness,
    created_at,
    updated_at
) VALUES (
    800,
    'yoon.seoyeon@example.com',
    '$2a$10$4pyW8SwZmR0msFWv5RxWfu.xO0mo0vQZiZGaG7ZQDjY.UQMB6thDa',
    '윤서연',
    '윤서연',
    '1995-12-18',
    'FEMALE',
    '010-8001-0001',
    'HELPER',
    'ACTIVE',
    'https://example.com/profiles/member800.jpg',
    '서울특별시 종로구 평창동',
    '안녕하세요, 윤서연입니다. 친절하게 도와드리겠습니다.',
    37.6106,
    127.0099,
    '1117010100',
    40.00,
    NOW(),
    NOW()
);

-- 회원 9: 도우미 (임동현, 30대 남성)
INSERT INTO member (
    member_id,
    email,
    password,
    name,
    nickname,
    birth_date,
    gender,
    phone_number,
    role,
    status,
    profile_image_url,
    address_road,
    introduction,
    latitude,
    longitude,
    district_code,
    sweetness,
    created_at,
    updated_at
) VALUES (
    900,
    'lim.donghyun@example.com',
    '{bcrypt}$2a$10$8.UnVuG9HHgffUDAlk8qfOuVGkqRzgVymGe07xd00DMxs.TVuHOnu',
    '임동현',
    '임동현',
    '1988-04-22',
    'MALE',
    '010-9001-0001',
    'HELPER',
    'ACTIVE',
    'https://example.com/profiles/member900.jpg',
    '서울특별시 은평구 응암동',
    '안녕하세요, 임동현입니다. 책임감 있게 도와드리겠습니다.',
    37.6388,
    127.0255,
    '1132010100',
    40.00,
    NOW(),
    NOW()
);

-- 회원 10: 도우미 (한미래, 30대 여성)
INSERT INTO member (
    member_id,
    email,
    password,
    name,
    nickname,
    birth_date,
    gender,
    phone_number,
    role,
    status,
    profile_image_url,
    address_road,
    introduction,
    latitude,
    longitude,
    district_code,
    sweetness,
    created_at,
    updated_at
) VALUES (
    1000,
    'han.mirae@example.com',
    '{bcrypt}$2a$10$8.UnVuG9HHgffUDAlk8qfOuVGkqRzgVymGe07xd00DMxs.TVuHOnu',
    '한미래',
    '한미래',
    '1992-06-08',
    'FEMALE',
    '010-1000-0001',
    'HELPER',
    'ACTIVE',
    'https://example.com/profiles/member1000.jpg',
    '서울특별시 도봉구 방학동',
    '안녕하세요, 한미래입니다. 밝은 마음으로 도와드리겠습니다.',
    37.6500,
    127.0322,
    '1135010100',
    40.00,
    NOW(),
    NOW()
);